# Generated by Django 3.0.4 on 2020-03-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printercontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='status',
            field=models.CharField(default='disconnected', max_length=12),
        ),
    ]
